### PR TITLE
Adding symlink support

### PR DESCRIPTION
**Pull request by seryl**

### CODE REVIEW

**Comment by seryl** [comment]
This ticket is part of a pull request that had started re: homebrew.

https://github.com/mxcl/homebrew/pull/18669

A seperate, independent pull request is required for riak_cs: https://github.com/basho/riak_cs/pull/550

Adds support for symlinks, it should work for riak-cs and stanchion.

I am not super familiar with the build process, but I'd like to get this tested and eventually merged.

Is there anyone who can give a little input? I can at a minimum test centos and osx.

**Comment by jaredmorrow** [comment]
I will happily take a look next time I'm near my machine, thanks for the PR.

**Comment by jaredmorrow** [comment]
These lines `{runner_script_dir,  "{{platform_bin_dir}}"}.` can't be removed because the `platform_bin_dir` is used for installing the app in different directories on different platforms.  In addition, you can't figure out the path of the `RUNNER_SCRIPT_DIR` based on any path from the env.sh as the env.sh might be installed somewhere completely different than the runner script.

**Comment by seryl** [comment]
I'll update it this evening with fixes

**Comment by xpe** [comment]
Any chance that this particular issue would help over at: https://github.com/mxcl/homebrew/pull/21155 -- updating homebrew recipe for Riak 1.4.0? Homebrew likes symlinks, but adjusting the Riak install for them is painful.

**Comment by jaredmorrow** [comment]
Something like this, but not the whole PR as it gets rid of functionality of other OS's by removing platform_bin_dir.

I was working on getting this https://github.com/erbmicha/homebrew/commit/77ede3af356fb3f02b18e2e697082dcbbd95f88d integrated.

**Pull request closed without merging**
