### PR TITLE
Require root or runner privs to run `ping` command

### PR DESCRIPTION
**Pull request by jaredmorrow**
Addresses: basho/riak#561

In certain cases, if `riak ping` was run before `riak start` (or any
other command) a `.erlang.cookie` file was created with the wrong
privs (in this case a root user) that prevented the riak user from
starting erlang.

### CODE REVIEW

**Comment by jaredmorrow** [comment]
Use the following packages to test:
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/debian/6/riak_2.0.0beta7-c9b9d12d-1_amd64.deb
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/debian/6/riak_2.0.0beta7-c9b9d12d-1_amd64.deb.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/debian/7/riak_2.0.0beta7-c9b9d12d-1_amd64.deb
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/debian/7/riak_2.0.0beta7-c9b9d12d-1_amd64.deb.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/fedora/19/riak-2.0.0beta7.c9b9d12d-1.fc19.src.rpm
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/fedora/19/riak-2.0.0beta7.c9b9d12d-1.fc19.src.rpm.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/fedora/19/riak-2.0.0beta7.c9b9d12d-1.fc19.x86_64.rpm
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/fedora/19/riak-2.0.0beta7.c9b9d12d-1.fc19.x86_64.rpm.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/freebsd/10/riak-2.0.0beta7-c9b9d12d.txz
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/freebsd/10/riak-2.0.0beta7-c9b9d12d.txz.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/freebsd/9.2/riak-2.0.0beta7-c9b9d12d-FreeBSD-amd64.tbz
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/freebsd/9.2/riak-2.0.0beta7-c9b9d12d-FreeBSD-amd64.tbz.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/osx/10.8/riak-2.0.0beta7-c9b9d12d-OSX-x86_64.tar.gz
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/osx/10.8/riak-2.0.0beta7-c9b9d12d-OSX-x86_64.tar.gz.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/rhel/5/riak-2.0.0beta7.c9b9d12d-1.el5.x86_64.rpm
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/rhel/5/riak-2.0.0beta7.c9b9d12d-1.el5.x86_64.rpm.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/rhel/5/riak-2.0.0beta7.c9b9d12d-1.src.rpm
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/rhel/5/riak-2.0.0beta7.c9b9d12d-1.src.rpm.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/rhel/6/riak-2.0.0beta7.c9b9d12d-1.el6.src.rpm
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/rhel/6/riak-2.0.0beta7.c9b9d12d-1.el6.src.rpm.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/rhel/6/riak-2.0.0beta7.c9b9d12d-1.el6.x86_64.rpm
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/rhel/6/riak-2.0.0beta7.c9b9d12d-1.el6.x86_64.rpm.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/riak-2.0.0beta7-c9b9d12d.tar.gz
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/sles/11/riak-2.0.0beta7.c9b9d12d-1.SLES11.x86_64.rpm
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/sles/11/riak-2.0.0beta7.c9b9d12d-1.SLES11.x86_64.rpm.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/sles/11/riak-2.0.0beta7.c9b9d12d-1.src.rpm
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/sles/11/riak-2.0.0beta7.c9b9d12d-1.src.rpm.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/ubuntu/lucid/riak_2.0.0beta7-c9b9d12d-1_amd64.deb
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/ubuntu/lucid/riak_2.0.0beta7-c9b9d12d-1_amd64.deb.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/ubuntu/precise/riak_2.0.0beta7-c9b9d12d-1_amd64.deb
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/ubuntu/precise/riak_2.0.0beta7-c9b9d12d-1_amd64.deb.sha
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/ubuntu/trusty/riak_2.0.0beta7-c9b9d12d-1_amd64.deb
- http://s3.amazonaws.com/builds.basho.com/riak/jem-source-default-scripts/2.0.0beta7-3-gb9a1ee9/ubuntu/trusty/riak_2.0.0beta7-c9b9d12d-1_amd64.deb.sha

**Comment by jaredmorrow** [comment]
/cc @jburwell @hectcastro 

I will address @glickbot's ENV variable issue https://github.com/basho/riak/issues/563 when we confirm this first step works.

**Comment by jaredmorrow** [comment]
I tested on ubuntu 12.04 with this simply:

```
vagrant@precise64:~$ sudo dpkg -i riak_2.0.0beta7-c9b9d12d-1_amd64.deb
Selecting previously unselected package riak.
(Reading database ... 51095 files and directories currently installed.)
Unpacking riak (from riak_2.0.0beta7-c9b9d12d-1_amd64.deb) ...
Setting up riak (2.0.0beta7-c9b9d12d-1) ...
Adding group `riak' (GID 111) ...
Done.
Adding system user `riak' (UID 106) ...
Adding new user `riak' (UID 106) with group `riak' ...
Not creating home directory `/var/lib/riak'.
Processing triggers for ureadahead ...
ureadahead will be reprofiled on next reboot
Processing triggers for man-db ...
vagrant@precise64:~$ sudo service riak start
!!!!
!!!! WARNING: ulimit -n is 1024; 65536 is the recommended minimum.
!!!!
vagrant@precise64:~$ ls -la /var/lib/riak
total 36
drwxr-xr-x  8 riak riak 4096 Jun 25 19:03 .
drwxr-xr-x 36 root root 4096 Jun 25 19:02 ..
drwxrwxr-x  4 riak riak 4096 Jun 25 19:03 anti_entropy
drwxrwxr-x  4 riak riak 4096 Jun 25 19:03 bitcask
drwxrwxr-x  3 riak riak 4096 Jun 25 19:03 cluster_meta
-r--------  1 riak riak   20 Jun 25 00:00 .erlang.cookie
drwxrwxr-x  2 riak riak 4096 Jun 25 19:03 generated.configs
drwxrwxr-x  2 riak riak 4096 Jun 25 19:03 kv_vnode
drwxr-xr-x  2 riak riak 4096 Jun 25 19:03 ring
vagrant@precise64:~$ service riak ping
You need to be root or use sudo to run this command
vagrant@precise64:~$ sudo service riak ping
pong
vagrant@precise64:~$ riak ping
You need to be root or use sudo to run this command
vagrant@precise64:~$ sudo riak ping
pong
```

**Comment by hectcastro** [comment]
I ran similar tests on the following platforms with success:
- ubuntu-1404
- ubuntu-1204
- centos-65
- centos-510
- debian-74
- debian-608

**Comment by jaredmorrow** [comment]
Awesome @hectcastro thanks for giving that a go.  I'll wait on @jburwell since he seems to run into the issue more than I do.

After that I'll figure out where the best place to source those default scripts.  We'll need to do it early, but not so early that it gets lost before the `su` call.

**Comment by jburwell** [comment]
Tested and passed on the following platforms:
- Ubuntu 12.04.4
- CentOS 6.5
- Debian 7.4

Reviewed the code modification. 

+1

**Pull request merged**
