### PR TITLE
Handle net_ticktime argument specially. Resolves RIAK-1281

### PR DESCRIPTION
**Pull request by seancribbs**
`escript` does not process emulator/runtime arguments like `erl`, so you can't
blindly pass an application environment setting on the command line. This
meant that the `-kernel net_ticktime N` argument passed to nodetool was not
functioning as intended and being treated as regular arguments, resulting in a
crash.

The net_ticktime setting is also a sensitive setting and should likely be set
before the Erlang distribution is started. I can only assume that the original
author that added it had intended for it to be loaded by the
application_controller, as `erl` does.

Therefore, this change handles net_ticktime specially in 
nodetool:process_args/3 and puts it as the first argument to the script so
that it is set first.

### CODE REVIEW

**Comment by seancribbs** [comment]
@gcymbalski @slfritchie

**Comment by gcymbalski** [comment]
Looks reasonable to me!
+1

**Comment by seancribbs** [comment]
@gcymbalski Were you able to test it?

**Comment by slfritchie** [comment]
+1 60b6feb

I checked out riak's develop branch, `make`, then checked out this branch of the deps/node_package repo, `make stage`, then added the following to rel/riak/etc/riak.conf:

```
erlang.distribution.net_ticktime = 5
```

Then ran `rel/riak/bin/riak console` and was able to verify that `net_kernel:get_net_ticktime().` returns 5.  Same for `riak attach`, then use `Control-g`, then `s`, then `c` to get a shell on the _local_ Erlang VM, then verify that the tick time is also 5.

```
Erlang R16B02-basho5 (erts-5.10.3) [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V5.10.3  (abort with ^G)
(riak@127.0.0.1)1> 
User switch command
 --> s
 --> c
Eshell V5.10.3  (abort with ^G)
(c_45903_riak@127.0.0.1)1> net_kernel:get_net_ticktime().
5
```

**Comment by seancribbs** [comment]
Thanks @slfritchie @gcymbalski!

**Comment by randysecrist** [comment]
nice; thanks Sean!

**Pull request merged**
