### PR TITLE
Add support for -kernel net_ticktime

### PR DESCRIPTION
**Pull request by slfritchie**
Addresses https://github.com/basho/riak_core/pull/489

### CODE REVIEW

**Comment by jaredmorrow** [comment]
Can you explain what should happen in both the situation of having cuttlefish (fresh 2.0 install) and not having cuttlefish (upgraded 1.4.x config with vm.args / app.config)?  This will give me an idea on how to test this and what to look for.

Thanks.

**Comment by slfritchie** [comment]
`vm.args` is like OTP's behavior has always been: `-kernel net_ticktime SomeNumberOfSeconds`.  The cuttlefish doodad will add that line to the generated vm.args if `erlang.distribution.net_ticktime` is in the config and, if missing, add nothing.

**Comment by kellymclaughlin** [comment]
Verified that this PR along with [this](https://github.com/basho/cuttlefish/pull/133) cuttlefish PR resolves the issues I reported [here](https://github.com/basho/riak_core/pull/489).

**Comment by jaredmorrow** [comment]
That's good enough for me then.  You can merge whenever the stars align for you @slfritchie

**Pull request merged**
