### PR TITLE
Cleanup usage documentation for chkconfig

### LINKED ISSUE #147: Help text for chkconfig is broken
This is the output from `riak help`:

```
    chkconfig
        Confirms whether the app.config is valid.

        For applications configured with cuttlefish, this includes a call
        to  also
```

The missing text between "to" and "also" is "config generate"; it probably should also be explicit that it checks both `riak.conf` and `advanced.config`.

### PR DESCRIPTION
**Pull request by hectcastro**
Usage documentation for the `chkconfig`, `config`, and `config generate` subcommands contained some unescaped backticks. Those unescaped characters were preventing the text within them from being visible.

In addition, I added explicit references to the configuration files (`{{package_name}}.conf` and `advanced.config`) inspected by the subcommands.

This pull request aims to resolve https://github.com/basho/node_package/issues/147.

/cc @macintux

### CODE REVIEW

**Comment by jaredmorrow** [comment]
I'll review.  At first glance, I don't think you'll be able to use {{package_name}} for cases of this being a devrel, but maybe that doesn't matter.

**Comment by jaredmorrow** [comment]
@hectcastro 

`s/{{package_name}}/$SCRIPT/` and I'm +1

**Comment by hectcastro** [comment]
Addressed reference to unrenderable `{{package_name}}` in https://github.com/basho/node_package/commit/152cd9631467a0441118c8513b971fb18e6c1b16.

**Comment by jaredmorrow** [comment]
Thanks man, +1

**Pull request merged**
