### PR TITLE
Add support for short node name

### PR DESCRIPTION
**Pull request by systra**

### CODE REVIEW

**Comment by jaredmorrow** [comment]
Similar work is being done in rebar on their templates (which node_package is quite similar to) in this PR https://github.com/rebar/rebar/pull/115.  As I noted in there, `hostname -f` and `hostname -s` are not portable to Solaris variants and some BSD variants.

One solution might be to work with the rebar PR to get it portable since that will have more eyes, and we can port that final solution to node_package.

What do you think @systra?

**Comment by systra** [comment]
You're right. I didn't test it on Solaris nor BSD but what if I get rid of `hostname` switches by changing it to:
`NAME_HOST=`hostname | sed -e 's/\([^.]*\).*$/@\1/'``
for short names, and to:
`NAME_HOST="@"`hostname``
for long one?

Do you think it will work for other platforms as well?

**Comment by jaredmorrow** [comment]
Sorry, I'm going out of town for two weeks, I probably won't be able to review this until I get back.  Sorry for the long delay, I was waiting a bit for the rebar/rebar#115 PR to complete so we can make sure node_package and rebar have the same solution.  That PR just finished.  I can take a look at both when I get back or you can do it while I'm gone and see which method you prefer.

Thanks for the PR and sorry for the delay @systra

**Comment by jaredmorrow** [comment]
With our new configuration stuff #86, we've decided it was best to stop supporting `-sname` due to the problems it causes in production systems.  Sorry to let this PR sit here for so long.  

The `console-clean` code you added seems useful though if you want to put that in a new PR.

**Pull request closed without merging**
