### PR TITLE
force nodetool's encoding to be unicode

### PR DESCRIPTION
**Pull request by jrwest**
This PR changes nodetool from using latin1 (character set and encoding) to UTF-8 encoded Unicode characters. This affects how nodetool decodes input from the command-line & stdin, and how it encodes to stdout. 

To force the use of UTF-8 and because escripts default to latin1 [1] [2], `io:setopts/1` [1] is used to set the encoding for the standard IO devices to `utf8`.

To force command-line arguments to be decoded from UTF-8 into a Erlang list of unicode codepoints, reliably across platforms, the `+fnu` argument is added to nodetool via escript's vm arguments comment. The `+fnu` flag controls whether or not Erlang assumes filenames are represented in some Unicode encoding (usually UTF-8), referred to as "Unicode File Name Translation" or encoded in latin1, "bytewise encoding". On OS X and Windows Unicode File Name Translation is enabled by default. On Linux, it is not.  Adding `+fnu` has the effect of changing it for all platforms.  [3] indicates that command-line (and environment variables)  are assumed to be encoded in the same way as file names.  All the details can be found in [4] and [5].  

[1] http://erlang.org/doc/man/io.html#setopts-1
[2] http://erlang.org/pipermail/erlang-questions/2014-March/078154.html
[3] http://www.erlang.org/doc/apps/stdlib/unicode_usage.html#id62041
[4] http://erlang.org/pipermail/erlang-questions/2014-March/078329.html
[5] http://www.erlang.org/doc/apps/stdlib/unicode_usage.html

### CODE REVIEW

**Comment by macintux** [comment]
This did the trick when tested against my bucket type/utf8 changes. I will also test against my security/utf8 work.

**Comment by jrwest** [comment]
updated and forced pushed:
- using `utf8` instead of `unicode` since its more correct, although to erlang they mean the same thing
- added +fnu for reasons i need to sit down, type up and explain (since the Erlang docs leave me at a loss)....but it seems to work (verified on OS X by @reiddraper)

**Comment by reiddraper** [comment]
Looks good to me. [Here's](http://erlang.org/pipermail/erlang-questions/2014-March/078329.html) the related Erlang-Questions thread.

**Comment by lordnull** [comment]
Works as advertised. :+1:

**Pull request merged**
