### PR TITLE
Change nodetool to permit zero parameter rpc calls

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Change nodetool so that functions of zero arity may be called using
the supplied rpc facility. This is done by making a distinction
between the case when rpc parameters are present and when they are
not.

Previously calling zero arity functions has not been possible because
even submitting no rpc parameters is treated the same as submitting
the request with a single parameter of an empty list.  Nodetool
encapsulates any parameters as a list and the result of attempting to
call a function that takes no parameters was the rpc function calling
the supplied function with a single parameter of an empty list.

This change does not preclude calling functions with a single
parameter of an empty list. It just now makes that decision explicit
on the part of the caller.

### CODE REVIEW

**Comment by kuenishi** [comment]
+1, works as advertised

**Comment by kellymclaughlin** [comment]
I'll wait for some input from @jaredmorrow before merging. Since this repo was just branched for 2.0 maybe I should reopen against that branch for more cohesive tagging?

**Comment by jaredmorrow** [comment]
You want this in 2.0 or no?

**Comment by kellymclaughlin** [comment]
> You want this in 2.0 or no?

I'd like it for Riak CS 1.5, but that is independent of 2.0 at this point.

**Comment by jaredmorrow** [comment]
+1 to this just merging in here, I'll come back to it at RC2 if things are looking well on CS 1.5

**Pull request merged**
