### PR TITLE
Restart the old-fashioned way

### PR DESCRIPTION
**Pull request by macintux**
Related to #131, and per discussions with cliserv, `restart` isn't all that reliable. Here's a semantic change that may or may not be the way we want to proceed, but since I was in the mood to do something about it, here it be.

Worked "properly" (per the new semantic) in simple testing.

/cc @jaredmorrow @lukebakken

### CODE REVIEW

**Comment by macintux** [comment]
It occurred to me later that I didn't attempt to handle the case where stop failed (by not attempting a start); on the other hand, I'm not certain, that's the right thing to do. Maybe blindly trying to start it is best in case it does in fact stop.

**Comment by reiddraper** [comment]
Is this new code, or a 'revert' to the way it used to work? If so, what's the SHA of the old code?

**Comment by macintux** [comment]
Maybe @jaredmorrow knows otherwise, but I'm not aware of any previous incarnation of this behavior.

**Comment by reiddraper** [comment]
Ah, when I read 'the old-fashioned way', I was thinking that meant the way 'it used to work'. Carry on.

**Comment by macintux** [comment]
Gotcha. No, just John trying to be too clever. "The blue collar way"

**Comment by reiddraper** [comment]
Ha, fair enough.

**Comment by reiddraper** [comment]
Testing with Riak now. @macintux what do you think about amending the commit to include a more detailed commit message? And maybe a comment about `restart` continuing to try and start the node, even if the stop failed?

**Comment by reiddraper** [comment]
I've done the following to review:
- Read through the code
- Test this branch of node_package with Riak
- Check for bashisms (`checkbashisms priv/base/runner`)

+1 from me. Might be wise to have @jaredmorrow take a look as well though.

**Comment by macintux** [comment]
I'll update the commit message

**Comment by jaredmorrow** [comment]
+1

**Comment by macintux** [comment]
All cleaned up

**Comment by jaredmorrow** [comment]
:+1:

**Pull request merged**
