### PR TITLE
added support for extra cuttlefish commands

### PR DESCRIPTION
**Pull request by joedevivo**
Added support for
- $runner config effective
- $runner config describe VARIABLE

### CODE REVIEW

**Comment by jaredmorrow** [comment]
Calling `riak config` does not print out any help describing the possible commands.

**Comment by jaredmorrow** [comment]
The `riak config describe` command should catch the arg count at the shell level to prevent leaking cuttlefish output through to the shell.

```
./bin/riak config describe 
cuttlefish's describe command required a variable to query.
Try `describe setting.name`
```

Users would most likely think, "what does a cuttlefish have to do with anything?"

**Comment by joedevivo** [comment]
That's actually hardcoded io:format in cuttlefish's escript. I can change the wording over there to be "The describe command...", but that shouldn't hold up this review.

**Comment by jaredmorrow** [comment]
No, what I'm saying is you can catch the fact that there are not enough params given to 'config describe' and print help.  That will tie into not enough params to 'config'

**Comment by joedevivo** [comment]
Ooooh. I get it.

**Comment by jaredmorrow** [comment]
https://github.com/basho/riak/blob/develop/rel/files/riak-admin#L199 bucket-type or security subcommands are good examples.

**Comment by jaredmorrow** [comment]
Nothing big, just minor user friendliness fixes.

**Comment by joedevivo** [comment]
Yeah, that's the whole point of the cuttlefish stuff, so I'm all for this kind of attention

**Comment by jaredmorrow** [comment]
+1

**Pull request merged**
