### PR TITLE
Merge 2.0 branch into develop [JIRA: TOOLS-131]

### PR DESCRIPTION
**Pull request by jadeallenx**
Make `develop` branch the focus of current development across all repos. 

TODO: Tag develop once merged.

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
@mrallen1 I was about to make a PR for this and saw that you did it. Yet, I had a couple questions as a few minor 2.0 commits are not listed here (maybe for a specific reason). Hit me up on hipchat when you have time.

**Comment by mrallen1** [comment]
@zeeshanlakhani As we discussed going to close this for you to do a  little more comprehensive PR.

**Comment by jadeallenx** [comment]
Like a bad penny...

**Comment by seancribbs** [comment]
:+1:

**Comment by engelsanchez** [comment]
Hey @zeeshanlakhani: I restored the 2.0 branch.  It's not a good idea to remove release branches even if no further development is to happen on those yo.

**Comment by zeeshanlakhani** [comment]
@engelsanchez fat-fingered... wouldn't do it on purpose :).

**Comment by DSomogyi** [comment]
create jira issue

**Pull request merged**
